### ISSUE TITLE
Feature Request: FAQ Page

### ISSUE THREAD

**Issue by mhmohona** [WasmEdge/docs#73] opened 2023-05-22 05:01 UTC
### Describe the solution you'd like.

As a developer of WasmEdge, I believe that having an FAQ section would greatly benefit the community. It would provide a centralized location for addressing common queries, clarifying key concepts, and helping users troubleshoot common issues. 

### Additional context.

I would like to suggest including the following topics in the FAQ section:

- How does WasmEdge work internally?
- What programming languages are supported by WasmEdge?
- What are the different types of WasmEdge?
- What are the different ways to use WasmEdge?
- What are the different features of WasmEdge?
- What are the performance benefits of using WasmEdge?
- What are the security benefits of using WasmEdge?
- What are the development benefits of using WasmEdge?
- What is the difference between WasmEdge and other Wasm runtimes such as Node.js or WebAssembly?
- Can I use WasmEdge for running serverless functions?
- How do I integrate WasmEdge with other applications and frameworks?
- How do I host a Wasm module on WasmEdge?
- What security features does WasmEdge provide?
- How does WasmEdge handle errors and exceptions in Wasm modules?
- Can I use WasmEdge for machine learning inference?
- How do I debug my Wasm modules running on WasmEdge?

**Comment by Lucif3r-in** [comment] 2023-05-25 07:34
@mhmohona I would like to work on this. Can you guide me where to add the FAQ and the contents to be included inside the above points you have provided?

**Comment by adithyaakrishna** [comment] 2023-10-21 13:22
@mhmohona Could you please lmk if you have any updates on this PR?

**Comment by adithyaakrishna** [comment] 2023-10-21 13:24
@mhmohona This seems to be a duplicate of #37, can we go ahead and close this?

**Closed** 2023-10-21 13:29 UTC
Labels: enhancement
